# Базовый образ Airflow
FROM apache/airflow:2.10.3
#FROM apache/airflow:slim-3.0.0-python3.12
# Установка зависимостей Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование DAG-файлов
COPY dags /usr/local/airflow/dags

# Выполнение миграций базы данных Airflow
#RUN airflow db migrate

