version: '3.8'

services:

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8124:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - ./data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=crypto
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=secret
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - dwh-network

  extractor:
    container_name: extractor
    build:
      context: ./extractor
      dockerfile: Dockerfile
    depends_on:
      clickhouse-server:
        condition: service_healthy
    networks:
      - dwh-network

  web-dashboard:
    container_name: web-dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # HTTP interface
    networks:
      - dwh-network

networks:
  dwh-network:
    driver: bridge